config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :events
  resources :communities
  resources :gnomeparcels
  devise_for :users
  root to: "home#index"
  get 'home/contact'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/gnomeparcel.rb
class Gnomeparcel < ApplicationRecord
  belongs_to :user
end

app/controllers/gnomeparcels_controller.rb
class GnomeparcelsController < ApplicationController
  before_action :set_gnomeparcel, only: %i[ show edit update destroy ]
  before_action :owner, only: %i[ edit update destroy ]
  before_action :landcheck, only: %i[ new ]

  def landcheck
    unless current_user.has_land?
      flash[:notice] = 'You need land in order to create a new Gnomeparcel.'
      redirect_back(fallback_location: root_path)
    end 
  end

  def owner
    unless @gnomeparcel.user == current_user
      flash[:alert] = 'Not Your Land.'
      redirect_back(fallback_location: root_path)
    end 
  end





  # GET /gnomeparcels or /gnomeparcels.json
  def index
    @gnomeparcels = Gnomeparcel.all
  end

  # GET /gnomeparcels/1 or /gnomeparcels/1.json
  def show
  end

  # GET /gnomeparcels/new
  def new
    @gnomeparcel = Gnomeparcel.new
  end

  # GET /gnomeparcels/1/edit
  def edit
  end

  # POST /gnomeparcels or /gnomeparcels.json
  def create
    @gnomeparcel = Gnomeparcel.new(gnomeparcel_params)
    @gnomeparcel.user = current_user

    respond_to do |format|
      if @gnomeparcel.save
        format.html { redirect_to gnomeparcel_url(@gnomeparcel), notice: "Gnomeparcel was successfully created." }
        format.json { render :show, status: :created, location: @gnomeparcel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gnomeparcel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gnomeparcels/1 or /gnomeparcels/1.json
  def update
    respond_to do |format|
      if @gnomeparcel.update(gnomeparcel_params)
        format.html { redirect_to gnomeparcel_url(@gnomeparcel), notice: "Gnomeparcel was successfully updated." }
        format.json { render :show, status: :ok, location: @gnomeparcel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gnomeparcel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gnomeparcels/1 or /gnomeparcels/1.json
  def destroy
    @gnomeparcel.destroy

    respond_to do |format|
      format.html { redirect_to gnomeparcels_url, notice: "Gnomeparcel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gnomeparcel
      @gnomeparcel = Gnomeparcel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gnomeparcel_params
      params.require(:gnomeparcel).permit(:landaddress, :open_to_visitors, :open_to_new_members, :latlong, :waterbodies, :maps, :population, :maxcapacity, :vision, :landhookups, :roadaccess, :seasonalhazards, :water, :electric, :sewage, :wifi, :user_id)
    end
end

app/helpers/gnomeparcels_helper.rb
module GnomeparcelsHelper
end

app/views/gnomeparcels/_form.html.erb
<%= form_with(model: gnomeparcel) do |form| %>
  <% if gnomeparcel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gnomeparcel.errors.count, "error") %> prohibited this gnomeparcel from being saved:</h2>

      <ul>
        <% gnomeparcel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :landaddress %>
    <%= form.text_area :landaddress %>
  </div>

  <div class="field">
    <%= form.label :open_to_visitors %>
    <%= form.check_box :open_to_visitors %>
  </div>

  <div class="field">
    <%= form.label :open_to_new_members %>
    <%= form.check_box :open_to_new_members %>
  </div>

  <div class="field">
    <%= form.label :latlong %>
    <%= form.text_field :latlong %>
  </div>

  <div class="field">
    <%= form.label :waterbodies %>
    <%= form.number_field :waterbodies %>
  </div>

  <div class="field">
    <%= form.label :maps %>
    <%= form.text_area :maps %>
  </div>

  <div class="field">
    <%= form.label :population %>
    <%= form.number_field :population %>
  </div>

  <div class="field">
    <%= form.label :maxcapacity %>
    <%= form.number_field :maxcapacity %>
  </div>

  <div class="field">
    <%= form.label :vision %>
    <%= form.text_area :vision %>
  </div>

  <div class="field">
    <%= form.label :landhookups %>
    <%= form.number_field :landhookups %>
  </div>

  <div class="field">
    <%= form.label :roadaccess %>
    <%= form.check_box :roadaccess %>
  </div>

  <div class="field">
    <%= form.label :seasonalhazards %>
    <%= form.text_field :seasonalhazards %>
  </div>

  <div class="field">
    <%= form.label :water %>
    <%= form.check_box :water %>
  </div>

  <div class="field">
    <%= form.label :electric %>
    <%= form.check_box :electric %>
  </div>

  <div class="field">
    <%= form.label :sewage %>
    <%= form.check_box :sewage %>
  </div>

  <div class="field">
    <%= form.label :wifi %>
    <%= form.check_box :wifi %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gnomeparcels/edit.html.erb
<h1>Editing Gnomeparcel</h1>

<%= render 'form', gnomeparcel: @gnomeparcel %>

<%= link_to 'Show', @gnomeparcel %> |
<%= link_to 'Back', gnomeparcels_path %>

app/views/gnomeparcels/index.html.erb
<h1>Gnomeparcels</h1>

<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Landaddress</th>
      <th>Open to visitors</th>
      <th>Open to new members</th>
      <th>Latlong</th>
      <th>Waterbodies</th>
      <th>Maps</th>
      <th>Population</th>
      <th>Maxcapacity</th>
      <th>Vision</th>
      <th>Landhookups</th>
      <th>Roadaccess</th>
      <th>Seasonalhazards</th>
      <th>Water</th>
      <th>Electric</th>
      <th>Sewage</th>
      <th>Wifi</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gnomeparcels.each do |gnomeparcel| %>
      <tr>
        <td><%= gnomeparcel.landaddress %></td>
        <td><%= gnomeparcel.open_to_visitors %></td>
        <td><%= gnomeparcel.open_to_new_members %></td>
        <td><%= gnomeparcel.latlong %></td>
        <td><%= gnomeparcel.waterbodies %></td>
        <td><%= gnomeparcel.maps %></td>
        <td><%= gnomeparcel.population %></td>
        <td><%= gnomeparcel.maxcapacity %></td>
        <td><%= gnomeparcel.vision %></td>
        <td><%= gnomeparcel.landhookups %></td>
        <td><%= gnomeparcel.roadaccess %></td>
        <td><%= gnomeparcel.seasonalhazards %></td>
        <td><%= gnomeparcel.water %></td>
        <td><%= gnomeparcel.electric %></td>
        <td><%= gnomeparcel.sewage %></td>
        <td><%= gnomeparcel.wifi %></td>
        <td><%= gnomeparcel.user_id %></td>
        <td><%= link_to 'Show', gnomeparcel %></td>
        <td><%= link_to 'Edit', edit_gnomeparcel_path(gnomeparcel) %></td>
        <td><%= link_to 'Destroy', gnomeparcel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Gnomeparcel', new_gnomeparcel_path %>

app/views/gnomeparcels/new.html.erb
<h1>New Gnomeparcel</h1>

<%= render 'form', gnomeparcel: @gnomeparcel %>

<%= link_to 'Back', gnomeparcels_path %>

app/views/gnomeparcels/show.html.erb
<p>
  <strong>Landaddress:</strong>
  <%= @gnomeparcel.landaddress %>
</p>

<p>
  <strong>Open to visitors:</strong>
  <%= @gnomeparcel.open_to_visitors %>
</p>

<p>
  <strong>Open to new members:</strong>
  <%= @gnomeparcel.open_to_new_members %>
</p>

<p>
  <strong>Latlong:</strong>
  <%= @gnomeparcel.latlong %>
</p>

<p>
  <strong>Waterbodies:</strong>
  <%= @gnomeparcel.waterbodies %>
</p>

<p>
  <strong>Maps:</strong>
  <%= @gnomeparcel.maps %>
</p>

<p>
  <strong>Population:</strong>
  <%= @gnomeparcel.population %>
</p>

<p>
  <strong>Maxcapacity:</strong>
  <%= @gnomeparcel.maxcapacity %>
</p>

<p>
  <strong>Vision:</strong>
  <%= @gnomeparcel.vision %>
</p>

<p>
  <strong>Landhookups:</strong>
  <%= @gnomeparcel.landhookups %>
</p>

<p>
  <strong>Roadaccess:</strong>
  <%= @gnomeparcel.roadaccess %>
</p>

<p>
  <strong>Seasonalhazards:</strong>
  <%= @gnomeparcel.seasonalhazards %>
</p>

<p>
  <strong>Water:</strong>
  <%= @gnomeparcel.water %>
</p>

<p>
  <strong>Electric:</strong>
  <%= @gnomeparcel.electric %>
</p>

<p>
  <strong>Sewage:</strong>
  <%= @gnomeparcel.sewage %>
</p>

<p>
  <strong>Wifi:</strong>
  <%= @gnomeparcel.wifi %>
</p>

<p>
  <strong>User:</strong>
  <%= @gnomeparcel.user_id %>
</p>

<%= link_to 'Edit', edit_gnomeparcel_path(@gnomeparcel) %> |
<%= link_to 'Back', gnomeparcels_path %>