config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :events
  resources :communities
  resources :gnomeparcels
  devise_for :users
  root to: "home#index"
  get 'home/contact'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :gnomeparcel
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: %i[ show edit update destroy ]
  before_action :owner, only: %i[ edit update destroy ]

  def owner
    #pending update because this currently is just a clone of owner from gnomeparcels
    #update should check if current user is a member of the community instead of the one who created the record/admin... 
    #add nuance to each action authorization but for now to make sure people don't delete other ppls ish just using this
    unless @community.user == current_user
      flash[:alert] = 'Not Your Community.'
      redirect_back(fallback_location: root_path)
    end 
  end

  # GET /communities or /communities.json
  def index
    @communities = Community.all
  end

  # GET /communities/1 or /communities/1.json
  def show
  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities or /communities.json
  def create
    @community = Community.new(community_params)

    respond_to do |format|
      if @community.save
        format.html { redirect_to community_url(@community), notice: "Community was successfully created." }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1 or /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to community_url(@community), notice: "Community was successfully updated." }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1 or /communities/1.json
  def destroy
    @community.destroy

    respond_to do |format|
      format.html { redirect_to communities_url, notice: "Community was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def community_params
      params.require(:community).permit(:name, :mission, :calendar, :gnomeparcel_id)
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.erb
<%= form_with(model: community) do |form| %>
  <% if community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
        <% community.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :mission %>
    <%= form.text_area :mission %>
  </div>

  <div class="field">
    <%= form.label :calendar %>
    <%= form.text_area :calendar %>
  </div>

  <div class="field">
    <%= form.label :gnomeparcel_id %>
    <%= form.collection_select :gnomeparcel_id, Gnomeparcel.order(:landaddress),:id,:landaddress %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/communities/edit.html.erb
<h1>Editing Community</h1>

<%= render 'form', community: @community %>

<%= link_to 'Show', @community %> |
<%= link_to 'Back', communities_path %>

app/views/communities/index.html.erb
<h1>Communities</h1>

<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Mission</th>
      <th>Calendar</th>
      <th>Gnomeparcel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @communities.each do |community| %>
      <tr>
        <td><%= community.name %></td>
        <td><%= community.mission %></td>
        <td><%= community.calendar %></td>
        <td><%= community.gnomeparcel_id %></td>
        <td><%= link_to 'Show', community %></td>
        <td><%= link_to 'Edit', edit_community_path(community) %></td>
        <td><%= link_to 'Destroy', community, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Community', new_community_path %>

app/views/communities/new.html.erb
<h1>New Community</h1>

<%= render 'form', community: @community %>

<%= link_to 'Back', communities_path %>

app/views/communities/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @community.name %>
</p>

<p>
  <strong>Mission:</strong>
  <%= @community.mission %>
</p>

<p>
  <strong>Calendar:</strong>
  <%= @community.calendar %>
</p>

<p>
  <strong>Gnomeparcel:</strong>
  <%= @community.gnomeparcel_id %>
</p>

<%= link_to 'Edit', edit_community_path(@community) %> |
<%= link_to 'Back', communities_path %>